tunnel: ryuzu-dev-tunnnel
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  # Example TCP service configuration
  # - hostname: tcp.example.com
  #   service: tcp://service-name.namespace.svc.cluster.local:port
  # Example UDP service configuration  
  # - hostname: udp.example.com
  #   service: udp://service-name.namespace.svc.cluster.local:port
  
  # Catch-all rule (required)
  - service: http_status:404