apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  template:
    spec:
      containers:
      - name: cloudflared
        env:
        - name: CLOUDFLARE_TUNNEL_NAME
          valueFrom:
            secretKeyRef:
              name: cloudflare-api-copy
              key: cloudflare-tunnel-name