apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: cloudflared-config
    namespace: cloudflare-tunnel
    behavior: replace
    files:
      - config.yaml